### ISSUE TITLE
Punk Idea: create linux stories

### ISSUE THREAD

**Issue by DnyaneshwariKolapkar** [StreetCommunityProgrammer/metaphore#76]
### Tell me what you want to suggest

Instead of just stories for programming languages, users should also be able to add Linux-related stories. After dual booting sometimes users face problems and many of us come up with different solutions which we can put it here.

**Comment by darkterminal** [comment]
Hey there, Linux enthusiast! 🐧

You know what? I couldn't agree more! We all love a good programming language story, but why stop there? Let's dive into the wonderful world of Linux-related tales and adventures! 🚀

Dual booting can be a rollercoaster ride of emotions, am I right? One minute you feel like a tech genius, and the next, you're pulling your hair out in frustration! 😅 But fear not, my friend, because that's where the real magic lies - in those "Eureka!" moments when you stumble upon a brilliant solution!

I mean, who hasn't faced those pesky problems during dual booting? From bootloaders throwing tantrums to mysterious driver issues, it's like solving a tech puzzle, and we're all in it together! 💻

So, let's create a grand collection of Linux-related stories right here! Share your triumphs, your epic fails, and everything in between. We'll laugh, we'll cry (probably because of a mistyped command), and we'll learn together as a community.

I'll make one, it's very interesting!

**Comment by DnyaneshwariKolapkar** [comment]
Great! Let's get going... I have some Linux stories I'm excited to share.

**Comment by darkterminal** [comment]
This punk idea has been released in the new update of our metaphor! :rocket:

**Comment by DnyaneshwariKolapkar** [comment]
It is showing the Linux Stories option here https://metaphore.vercel.app/stories but when I try to create a new issue there's no option to create Linux story like it is for other programming languages.

**Comment by darkterminal** [comment]
Ah I forgot something!

**Comment by DnyaneshwariKolapkar** [comment]
yep! It's working.
